### ISSUE TITLE
AttendeesTableSeeder -  Illuminate\Database\QueryException 

### ISSUE THREAD

**Issue by moesaid** [OmarXCoder/mrw#21]
<img width="1641" alt="Screen Shot 2022-06-16 at 9 34 06 PM" src="https://user-images.githubusercontent.com/38924585/174204790-af3a7012-319e-469d-82aa-fae689185e92.png">

**Comment by OmarXCoder** [comment]
what DB provider do you use, MySql ?

**Comment by moesaid** [comment]
yes
